### ISSUE TITLE
Can not add the Tab component to my project: cp returned EINVAL

### ISSUE THREAD

**Issue by Alireza-Moh** [radix-vue/shadcn-vue#1121]
I got an error while attempting to add the Tab component to my project  `npx shadcn-vue@latest add tabs`
The error message indicates an invalid source or destination during the copy operation.

I'm working on WSL + Docker

```js
this is error:  Invalid src or dest: cp returned EINVAL (cannot copy /var/www/node_modules/glob/dist/esm/bin.mjs to a subdirectory of self /var/www/node_modules/glob/dist/esm/bin.mjs) /tmp/shadcn-vue/.bin/glob

    at onLink (node:internal/fs/cp/cp:348:11)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async updateFiles (/home/node/.npm/_npx/360157ef5dc9b5fb/node_modules/shadcn-vue/dist/index.js:1806:5)
    at async addComponents (/home/node/.npm/_npx/360157ef5dc9b5fb/node_modules/shadcn-vue/dist/index.js:1961:3)
    at async Command.<anonymous> (/home/node/.npm/_npx/360157ef5dc9b5fb/node_modules/shadcn-vue/dist/index.js:2431:5)

ERROR  Invalid src or dest: cp returned EINVAL (cannot copy /var/www/node_modules/glob/dist/esm/bin.mjs to a subdirectory of self /var/www/node_modules/glob/dist/esm/bin.mjs) /tmp/shadcn-vue/.bin/glob
```

**Comment by stevebauman** [comment]
Getting the same error. How did you resolve it?

**Comment by stevebauman** [comment]
Resolved it -- for those wondering, delete the whole temporary `shadcn-vue` folder that it tells you about in the error and then re-run adding a component. For example, my error output contained:

```
/var/folders/lj/grqmcckn0118hb0ldvtzt9780000gn/T/shadcn-vue/.bin/clean-orphaned-assets
```

So I deleted the whole folder below:

```
/var/folders/lj/grqmcckn0118hb0ldvtzt9780000gn/T/shadcn-vue
```

Then re-ran the installation. Could be because of an old shadcn-vue version in tmp?

**Comment by atymic** [comment]
Also getting the same error, any luck?
For me both paths are the same (in my app dir)

**Comment by Alireza-Moh** [comment]
I deleted the `node_modules` folder and the `package-lock.json`, then reinstalled everything again. That solved the issue for me.

**Comment by atymic** [comment]
This unf did not fix it for me :(
I also have old radix components, maybe that's part of the issue?

**Comment by Alireza-Moh** [comment]
> This unf did not fix it for me :(
> I also have old radix components, maybe that's part of the issue?

Which radix version are you using ?
